name: Lumi-CI

on:
  # Dispatch this workflow whenever master or dev get a PR or commit
  push:
    branches : ["dev","master"]
  pull_request:
    branches: ["dev","master"]
  # ... or when the workflow is started manually
  workflow_dispatch:

concurrency:
   group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
   cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Drop SSH key into VM
        run: |
          mkdir -p .ssh/
          echo "${{secrets.LUMI_SSH_KEY}}" > .ssh/id_lumi
          sudo chmod 600 .ssh/id_lumi
      - name: Set tag var
        id: vars
        run: echo "run_dir=$(mktemp -u vlasiator_ci_$(date +%Y%m%d%H%M%S)-XXXXXX)" >> $GITHUB_OUTPUT
      - name: Clone on Lumi
        run: |
          ssh -i .ssh/id_lumi -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=5 -o BatchMode=yes -o PasswordAuthentication=no -o IdentitiesOnly=yes lrb_462001599_ci@lumi.csc.fi "export rundir=${{ steps.vars.outputs.run_dir }}; echo $rundir; mkdir $rundir; cd $rundir; git clone --recurse-submodules https://github.com/fmihpc/vlasiator.git; cd vlasiator; git checkout ${{ github.ref }}; git submodule update --init --recursive;"
      - name: Build Libraries on Lumi
        run: |
          ssh -i .ssh/id_lumi -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=5 -o BatchMode=yes -o PasswordAuthentication=no -o IdentitiesOnly=yes lrb_462001599_ci@lumi.csc.fi "export rundir=${{ steps.vars.outputs.run_dir }}; echo $rundir; cd $rundir/vlasiator; export VLASIATOR_ARCH=lumi_cpeGnu; module purge; module load PrgEnv-gnu; module load gcc/10.3.0; module load craype-x86-milan; module load papi; ./fetch_and_build_libraries.sh;"
      - name: Build Vlasiator on Lumi
        run: |
          ssh -i .ssh/id_lumi -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=5 -o BatchMode=yes -o PasswordAuthentication=no -o IdentitiesOnly=yes lrb_462001599_ci@lumi.csc.fi "export rundir=${{ steps.vars.outputs.run_dir }}; echo $rundir; cd $rundir/vlasiator; export VLASIATOR_ARCH=lumi_cpeGnu; module purge; module load PrgEnv-gnu; module load gcc/10.3.0; module load craype-x86-milan; module load papi; make -j; #cd ../..; #rm -rf $rundir;"
